#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "Put OGScope online"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check the project builds"
say "Before touching any accounts, let's confirm the code is healthy."
say ""
if npm test --silent >/dev/null 2>&1; then
  say "Tests pass."
else
  warn "Tests failed. Run 'npm test' to see why before deploying."
  confirm "Carry on anyway?" || exit 1
fi
if npm run build --silent >/dev/null 2>&1; then
  say "Production build succeeded."
else
  warn "The build failed. Run 'npm run build' to see the error."
  exit 1
fi
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare account"
say "OGScope runs on Cloudflare Workers. The free plan covers 100,000 requests"
say "a day and allows commercial use, so this costs nothing."
say ""
note "No card is required for the free plan."
say ""
if confirm "Do you already have a Cloudflare account?"; then
  say "Good, we'll sign in with it next."
else
  open_url "https://dash.cloudflare.com/sign-up"
  step "Create the account with your email and a password."
  step "Confirm the address from the email Cloudflare sends you."
  pause "Press Enter once the account exists"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Connect this machine to Cloudflare"
say "This opens a browser window and asks you to authorise the deploy tool."
say ""
step "Press Allow on the page that opens."
say ""
if npx wrangler whoami >/dev/null 2>&1; then
  say "Already signed in."
else
  npx wrangler login || warn "Login did not complete. Re-run this wizard when it does."
fi
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Choose your address"
say "Two options:"
say ""
step "A free address like ogscope.workers.dev. Costs nothing, available now."
step "Your own domain, roughly 10 dollars a year. Better for search rankings."
say ""
note "You can start free and add a domain later. Nothing here is permanent."
say ""
say "Enter the full address you want, including https://"
note "Free example:   https://ogscope.workers.dev"
note "Custom example: https://ogscope.app"
ask PUBLIC_SITE_URL "Your site address:"
if [[ -z "${PUBLIC_SITE_URL:-}" ]]; then
  PUBLIC_SITE_URL="https://ogscope.workers.dev"
  note "Nothing entered, using $PUBLIC_SITE_URL for now."
fi
write_env PUBLIC_SITE_URL "$PUBLIC_SITE_URL"
say ""
note "This address goes into your canonical tags and sitemap, so it has to match"
note "where the site actually lives. Re-run this wizard if it changes."
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Deploy"
say "This uploads the site to Cloudflare. It takes under a minute."
say ""
if confirm "Deploy now?"; then
  npm run deploy || { warn "Deploy failed. The error above says why."; exit 1; }
  say ""
  say "Deployed."
  note "Cloudflare printed the live URL above."
else
  SKIPPED+=("Deploy: run 'npm run deploy' when ready")
fi
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Protect the scanner from abuse"
say "The /api/scan endpoint fetches whatever URL it is given. The code already"
say "blocks private networks, but a rate limit stops someone hammering it."
say ""
open_url "https://dash.cloudflare.com/?to=/:account/workers/services"
step "Open your 'ogscope' Worker."
step "Go to Settings, then Rate limiting."
step "Add a rule: 30 requests per minute, matching path /api/scan."
say ""
note "Skip this for now if you like. It matters once you have traffic, not before."
pause "Press Enter to continue"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Tell Google the site exists"
say "This is the step that actually brings visitors. The eight guide pages are"
say "written to rank for searches like 'linkedin preview not updating'."
say ""
open_url "https://search.google.com/search-console"
step "Add a property and enter: $PUBLIC_SITE_URL"
step "Verify ownership. The HTML tag method is easiest on Cloudflare."
step "Go to Sitemaps in the left menu."
step "Submit: sitemap.xml"
say ""
note "Expect nothing for a few weeks. Search traffic builds slowly, then compounds."
pause "Press Enter to continue"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Payments (optional)"
say "Only needed when you want to charge for the image API. The free checker"
say "works without any of this."
say ""
note "Stripe has no monthly fee. It takes a percentage per sale, so it costs"
note "nothing until you actually earn something."
say ""
if confirm "Set up the paid tier now?"; then
  open_url "https://dashboard.stripe.com/payment-links/create"
  step "Create a product called 'OGScope Image API'."
  step "Set the price to 12 USD, recurring monthly."
  step "Create the link, then copy the URL it gives you."
  ask PUBLIC_STRIPE_API_LINK "Paste the payment link:"
  if [[ -n "${PUBLIC_STRIPE_API_LINK:-}" ]]; then
    write_env PUBLIC_STRIPE_API_LINK "$PUBLIC_STRIPE_API_LINK"
    say ""
    note "Run 'npm run deploy' again to put the working button live."
  fi
else
  note "Skipped. The pricing page shows 'Checkout not connected yet' until you do this."
  SKIPPED+=("Stripe payment link: re-run this wizard to add it")
fi

finish
